### ISSUE TITLE
Reference to Kotlin variables, function arguments, and named parameters are always colored

### ISSUE THREAD

**Issue by Him188** [mallowigi/color-highlighter#100]
**Describe the bug**

References to function variables, function arguments, and named parameters are always colored.

```kotlin

fun Color(
    red: Float,
    green: Float,
    blue: Float,
    alpha: Float = 1f,
) {
    println("red = $red") // `$red` is colored
}

fun main() {
    Color(
        red = 1, // `red` is colored
    )
}
```

It does not make sense that the variables are colored.

Disabling 'Detect Color Properties' doesn't help.

**To Reproduce**

1. Create a Kotlin project
2. Paste the above code
3. References are colored

**Expected Behavior**

References are not colored.

**Environment**

- Plugin version: 14.0.0
- IDEA: Build #IU-223.8214.52, built on December 20, 2022

**Screenshots**

![image](https://user-images.githubusercontent.com/12100985/211041351-7b1aa2fc-0e81-4d46-a4fb-4ec6fabfdd60.png)

**Comment by mallowigi** [comment]
I don't have the time to improve this project. If you wish to help, be my guest.
