### ISSUE TITLE
Highlighting too aggressive - allow me to choose what to highlight

### ISSUE THREAD

**Issue by OndrejSpanel** [mallowigi/color-highlighter#101]
I find the current highlighting a bit too much aggressive. In some cases it highlights things which are not colors at all.

Short hex numbers in Scala sources:

![image](https://user-images.githubusercontent.com/6927223/214514953-c7a0c7e6-78a5-426d-bfad-88ca23fadf32.png)

Decimal numeric literals in Scala sources:

![image](https://user-images.githubusercontent.com/6927223/214520817-d9d9f1f8-4b9b-4377-b2f2-5ef5bc16d7a7.png)

I would like to have hex colors highlighted  only when starting with 0x or #.

I would also prefer not to have highlighted words which are color names, like `blue`. This is a bit annoying when the same word means a color or an object, like `orange` or `pumpkin`. I see this in data configuration YAML files, but I get it can happen anywhere.

**Describe the solution you'd like**

I would like settings which would allow me to tell which color notations to highlight and which not.

**Describe alternatives you've considered**

Another option would be not to highlight short numbers and color names at all, which would suit me, but this is perhaps not acceptable for other users.

**Comment by mallowigi** [comment]
Fair enough. Unfortunately I have no time to work on this project at all, so I currently have no indication when I'll be able to do so.

**Comment by OndrejSpanel** [comment]
I will try if perhaps I would be able to prepare a PR.

**Comment by mallowigi** [comment]
will be available next relese through settings
