### ISSUE TITLE
RGB Tuples not Recognizing in Python

### ISSUE THREAD

**Issue by Zer0-Official** [mallowigi/color-highlighter#108]
**Describe the bug**
When an RGB tuple is defined in a variable in Python (for pygame), colors do not appear. The other methods work, but not for the one I need.

**To Reproduce**
1. write an RGB tuple (example below)

**Expected Behavior**
the tuple should be highlighted with the color

It should contain:
* Windows
* PyCharm 2023 Professional
* Color Highlighter 14.0.0

**Screenshots**
![Screenshot (124)](https://user-images.githubusercontent.com/62067365/230748795-b4816902-c391-4095-8ae3-8c819356f6e2.jpg)

**Comment by mallowigi** [comment]
Thanks for the report but be aware that I'm not working on this project anymore for the time being. 

You're free to try fix it yourself though

**Comment by mallowigi** [comment]
will be available in next release

**Comment by Zer0-Official** [comment]
Thank you!
