### ISSUE TITLE
Recognize Hex Color Errors in Kotlin

### ISSUE THREAD

**Issue by FrankMilesFrms** [mallowigi/color-highlighter#109]
This is the color the plugin dispalys :

![image](https://user-images.githubusercontent.com/36991251/233430043-d46e8da8-c0e7-4f6e-afe0-bf95925d4773.png)

But this is the correct result:
![image](https://user-images.githubusercontent.com/36991251/233430446-deaf2dd4-cbca-4d89-9650-c69644aff18f.png)

**Comment by FrankMilesFrms** [comment]
The Hex color is not properly represented in kotlin.   Note: The latter shows images from android studio's built-in features

**Comment by mallowigi** [comment]
Have you tried this setting: "use rgba instead of argb"?

<img width="1088" alt="CleanShot 2023-04-20 at 19 43 14@2x" src="https://user-images.githubusercontent.com/5015756/233432898-c7b374e1-5828-476a-8611-298bd3c2b0f3.png">

**Comment by FrankMilesFrms** [comment]
Oh...You are right, thanks.

**Comment by bric3** [comment]
@mallowigi Couldn't that (arbg or rgba) be autodetected for `Color` or `JBColor` ?
