### ISSUE TITLE
Colors not showing for HTML and CSS, but shows for JS

### ISSUE THREAD

**Issue by eclectiv** [mallowigi/color-highlighter#112]
**Describe the bug**
The color highlighting doesn't work for my HTML and CSS files. However, they work fine for my JS files.

Is there a setting I need to change?

JS works.
![js](https://github.com/mallowigi/color-highlighter/assets/85909225/68b3ea2d-9fea-4398-b3c8-152b72969f95)

HTML and CSS don't.
![html](https://github.com/mallowigi/color-highlighter/assets/85909225/f42dfe6c-be51-4cee-8e9d-c008d5839fbe)
![css](https://github.com/mallowigi/color-highlighter/assets/85909225/80269fb8-97d7-476f-87b6-69cb84b795dd)

**Comment by mallowigi** [comment]
Have you tried turning that on:

![CleanShot 2023-08-09 at 21 44 47@2x](https://github.com/mallowigi/color-highlighter/assets/5015756/82d2a6f9-200c-4515-aa95-f3c97ab2a683)

I'll turn it on by default
