### ISSUE TITLE
Decimal numeric literals in Scala sources should not be highlighted

### ISSUE THREAD

**Issue by OndrejSpanel** [mallowigi/color-highlighter#124]
Originally described in now closed #101:

I find the current highlighting a bit too much aggressive. In some cases it highlights things which are not colors at all.

Decimal numeric literals in Scala sources:

![image](https://github.com/mallowigi/color-highlighter/assets/6927223/2ce430db-bc26-4938-9f2d-1c07be8cba99)

```
  val rng = new scala.util.Random(123456)
  val seeds = (0 until 10).map(_ => rng.nextInt(1000000))
```

I would like to have hex colors highlighted  only when starting with 0x or #.

**Comment by OndrejSpanel** [comment]
Note: it seems when the option "Detect hex colors" is not enabled, plain numbers without `0x` or `#` are not highlighted. Perhaps the option could be made more explicit, like "Detect hex color without prefix", or inverted "Detect hex colors only when prefixed with 0x or #".

**Comment by mallowigi** [comment]
I don't plan on releasing an update just for wording. Closing this as this is irrelevant.
