### ISSUE TITLE
Add Android color support

### ISSUE THREAD

**Issue by Modificator** [mallowigi/color-highlighter#30]
Useful tools !!
I try to add it, but I can't build this project,,,,missing some dependencies like: Pythonid,ruby

Android color format : 0x12345678 -> argb. a: 0x12, r: 0x34, g: 0x56, b: 0x78
also hava xml color: #12345678 or #235678

**Comment by mallowigi** [comment]
Why are you saying that your formats do not work? They look like working to me... can you provide a screenshot?

**Comment by Modificator** [comment]
- color in code (java/kotlin), should be black with alpha
   - ![image](https://user-images.githubusercontent.com/3425930/135221255-045c6d86-3313-4f27-b61b-f769fd89c302.png)
 - color in xml, small color block is right, `color-highlighter` is big one
    - ![image](https://user-images.githubusercontent.com/3425930/135221581-7bc8bf0c-91b7-423d-81b1-dd9643ed1add.png)

**Comment by mallowigi** [comment]
So the alpha is on the left rather than on the right? This sucks man this is not the standard for hex codes

**Comment by mallowigi** [comment]
Ok I will try to make it for the next version when I'll find the time. I just need to know if these files are identifiable differently than regular xml or Kotlin files

**Comment by Modificator** [comment]
No different, mobile(android/ios) is argb, web is rgba,, maybe can check ${ProjectRoot}/.idea/misc.xml  ProjectType

![image](https://user-images.githubusercontent.com/3425930/135228472-903e84af-5d27-4e58-a26a-e0705f83508e.png)

https://developer.android.com/guide/topics/resources/more-resources.html#Color
https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4

**Comment by mallowigi** [comment]
Fixed in 9.2
