### ISSUE TITLE
Hex numbers are not recognized

### ISSUE THREAD

**Issue by zz5840** [mallowigi/color-highlighter#36]
**Describe the bug**

Hex numbers like `0xffffff` are not recognized in typescript file, but the same format in strings can be recognized correctly.

The hex number format can be used in some of the WebGL renderer like [PIXI.js](https://pixijs.com/).

**Expected Behavior**

![image](https://user-images.githubusercontent.com/16662647/135067262-6f01359d-9f26-45a2-8467-311071d8d29a.png)
![image](https://user-images.githubusercontent.com/16662647/135067458-3acfdf1e-2779-4c2c-be1a-fe8aa9ffc5b3.png)

**Environment**

WebStorm 2021.2.1
Build #WS-212.5080.54, built on August 23, 2021
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1772M
Cores: 12
Non-Bundled Plugins: com.mallowigi.colorHighlighter (8.0)

**Comment by mallowigi** [comment]
Indeed, this is because I'm parsing only strings in regular languages, not numerals. Only in Java/Kotlin/Scala...

Too bad I just released a new version now that I've been working on for a while, so this will have to wait

**Comment by egel** [comment]
I'd love to see this feature 👍

**Comment by fran6co** [comment]
This doesn't work on C++ in Clion, I'm on version 12.0.0 and Clion 2022.2 on Ubuntu 22.04.

![image](https://user-images.githubusercontent.com/726088/184619265-8a827015-a07c-4f17-ac84-842476146f3a.png)

**Comment by teshca** [comment]
same with version 14.0.0
Doesn't work on C++ in Clion
[x] Detect hex color 
checked in settings, but only strings highlighted as in comment above
