### ISSUE TITLE
Feature Request: Themes with arbitrary color names

### ISSUE THREAD

**Issue by tminich** [mallowigi/color-highlighter#4]
This is probably a big effort, so I apologize =)

It would be awesome if the highlighter supported customizable themes that I can turn off and on individually for projects.

For example we are using Vuetify in our projects that includes classes for certain [Material Design colors](https://vuetifyjs.com/en/styles/colors/). It would be awesome if I could add these as a theme and get them highlighted in my code.

**Comment by mallowigi** [comment]
I'm afraid i dont understand the request

**Comment by tminich** [comment]
Currently the colors are hardcoded to the color name. I'd like to be able to change that and add my own color names. 

To make it flexible it would be awesome if such a set of `color name` to `color` mappings could be saved as a theme/schema and be toggled per project, similar to how support for JavaScript libraries can be toggled in `Languages & Frameworks -> JavaScript -> Libraries`

An individual theme setup could look similar to [this](https://github.com/huoguangjin/MultiHighlight#customize), although a simple mapping to a color could suffice.

**Comment by mallowigi** [comment]
I see. Definitely interesting. I don't know when I'll be able to work on it since I'm pretty busy at work. But yes, it can be useful/

Alternatively you can try to do it as well, I don't think it should be that hard :)

**Comment by tminich** [comment]
I'll take a look, could be some time though as I would have to do it at home in my spare time and my home PC is currently a mess in dire need of an upgrade XD
