### ISSUE TITLE
Feature Request: CSS variable support

### ISSUE THREAD

**Issue by nzy** [mallowigi/color-highlighter#5]
Hi, great work, thanks!

It would be awesome if the highlighter will support the css variables.

![Снимок экрана 2020-12-06 205703](https://user-images.githubusercontent.com/42046/101278225-c8376e80-3805-11eb-9e39-52e3b4076acc.jpg)

Anyway, thank you.

**Comment by nzy** [comment]
Hm, just started to work.

Not sure why, maybe IDE fixed its index.

Thanks anyway.

![Снимок экрана 2020-12-07 110719](https://user-images.githubusercontent.com/42046/101299071-69f9a280-387c-11eb-8032-ef2d8b95d4b0.jpg)

**Comment by mallowigi** [comment]
wow i didn't know that. But tbh there is a feature i'd love to implement is to be able to see the color from scss variables. But it's different from what the plugin is doing, which is to highlights colors, not variables.
