### ISSUE TITLE
Support for Dart and flutter

### ISSUE THREAD

**Issue by BMomani** [mallowigi/color-highlighter#64]
thank you for your awesome work
you support most languages but I see Dart is messing 

Could you please add the support for it, flutter is very popular nowadays
The default Inteiilj impl. is not good enough as you see

<img width="590" alt="Screenshot 2022-05-26 at 9 11 25 AM" src="https://user-images.githubusercontent.com/7019737/170427969-a9ff57d1-6385-4a9a-8671-2f2d2e160de2.png">

one more feature can we have any kind of color hints on evaluate expression result dialog

<img width="584" alt="Screenshot 2022-05-26 at 9 20 10 AM" src="https://user-images.githubusercontent.com/7019737/170429201-b0919e5d-c0cc-4bcf-b988-39750ccf93b4.png">

I want to see what primary color look like and there is no easy way to do it, a tooltip could help

**Comment by thomasdf** [comment]
Was this included in a release? I couldn't find support for Dart when I tested the plugin in Android Studio.

**Comment by mallowigi** [comment]
I have included basic support for Dart, which is detection inside strings. Nothing related to the evaluation window.

Also what version are you on?

**Comment by allanlaal** [comment]
@mallowigi please reopen this and rename "Support for Dart and Flutter int/hex non-string color codes"
