### ISSUE TITLE
please support Dart。please！please！please！

### ISSUE THREAD

**Issue by chjsun** [mallowigi/color-highlighter#76]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when …

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mallowigi** [comment]
What do you mean? Dart is supported

**Comment by chjsun** [comment]
look like

file:   
```homePage.dart```

code:   
```
ColorUtil.hex("#333333")
```

**Comment by mallowigi** [comment]
<img width="561" alt="CleanShot 2022-07-26 at 21 39 27" src="https://user-images.githubusercontent.com/5015756/181085799-96a931b8-cd72-4a97-8a83-23ead78b0b17.png">

**Comment by chjsun** [comment]
i'm so sorry，I use 'android studio'， use It's good to switch to 'interlij idea'

**Comment by mallowigi** [comment]
I see, I'll try to see if I can make it available for older versions
