### ISSUE TITLE
setting "use rgba instead of argb" actually works in the opposite

### ISSUE THREAD

**Issue by SanAndreaP** [mallowigi/color-highlighter#83]
**Describe the bug**
Checking the setting "use rgba instead of argb" actually makes the plugin parse hex values as ARGB instead of RGBA, essentially doing the opposite of the description.

**To Reproduce**
1. By Default it is not checked
2. hex colors seem off, noticed that these are parsed as RGBA
3. check the "use rgba instead of argb" setting
4. hex colors are now correct, since now it is parsing them in ARGB

**Expected Behavior**
Checking the setting "use rgba instead of argb" makes the plugin parse hex values as RGBA instead of ARGB, so either change the labeling of the setting (easy) or change the behavior.

**Environment**
```
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Licensed to [REDACTED]
Subscription is active until [REDACTED].
For non-commercial open source development only.
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.65-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Non-Bundled Plugins:
    com.github.leomillon.uuidgenerator (4.5.1)
    com.intellij.ideolog (203.0.30.0)
    GLSL (1.21)
    VisualVMLauncher (1.21.211.6085.0)
    com.github.catppuccin.jetbrains (1.0.9)
    org.sonarlint.idea (7.0.0.52289)
    com.demonwav.minecraft-dev (2022.2-1.5.20)
    com.mallowigi.colorHighlighter (12.0.0)
    no.tornado.tornadofx.idea (1.7.20.1)

Kotlin: 222-1.7.10-release-334-IJ4167.29
Current Desktop: XFCE
```

**Screenshots**

![Bildschirmfoto_2022-09-18_22-35-54](https://user-images.githubusercontent.com/1854863/190928172-0b1c4048-74df-46c0-a6d9-7eb3103216f7.png)

**Comment by mallowigi** [comment]
<img width="282" alt="CleanShot 2022-10-01 at 10 45 17@2x" src="https://user-images.githubusercontent.com/5015756/193398960-9dcf2b50-1b6d-4af4-b5ea-12da4848cbcf.png">

🤦🏽

**Comment by mallowigi** [comment]
fixed
